export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        secondary: "#4edea3",
        "on-surface-variant": "#c2c6d6",
        "surface-container-lowest": "#0e0e10",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-bright": "#39393b",
        "surface-container-highest": "#353437",
        "inverse-primary": "#005ac2",
        "surface-variant": "#353437",
        background: "#131315",
        "secondary-fixed": "#6ffbbe",
        "on-primary": "#002e6a",
        "error-container": "#93000a",
        "surface-tint": "#adc6ff",
        "secondary-fixed-dim": "#4edea3",
        "on-tertiary": "#472a00",
        "on-secondary-container": "#00311f",
        "on-background": "#e5e1e4",
        surface: "#131315",
        "on-error": "#690005",
        error: "#ffb4ab",
        "tertiary-container": "#ca8100",
        "on-error-container": "#ffdad6",
        "secondary-container": "#00a572",
        "on-primary-fixed-variant": "#004395",
        "inverse-on-surface": "#313032",
        "on-secondary-fixed-variant": "#005236",
        "on-tertiary-fixed": "#2a1700",
        "surface-container-high": "#2a2a2c",
        primary: "#adc6ff",
        "on-secondary": "#003824",
        "primary-fixed-dim": "#adc6ff",
        "on-tertiary-fixed-variant": "#653e00",
        "primary-fixed": "#d8e2ff",
        "surface-container-low": "#1c1b1d",
        "on-primary-fixed": "#001a42",
        "surface-dim": "#131315",
        "on-secondary-fixed": "#002113",
        outline: "#8c909f",
        "on-primary-container": "#00285d",
        "surface-container": "#201f22",
        "on-tertiary-container": "#3e2400",
        "tertiary-fixed": "#ffddb8",
        tertiary: "#ffb95f",
        "primary-container": "#4d8eff",
        "on-surface": "#e5e1e4",
        "outline-variant": "#424754",
        "inverse-surface": "#e5e1e4",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        "container-max": "1280px",
        "margin-mobile": "16px",
        gutter: "24px",
        "margin-desktop": "40px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        display: ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        display: ["48px", { lineHeight: "56px", letterSpacing: "-0.04em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
